version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./.env.local
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
